### ISSUE TITLE
Question: How to generate doc_api_v1.yml ?

### ISSUE THREAD

**Issue by mjm918** [fabienbellanger/axum-boilerplate#1]
Hi there, 

Thank you so much for the work. Your repository helped me a lot to kick start a project. 

I would like to ask, how did you generate the assets/documentation/doc_api_v1.yml file ?

**Comment by fabienbellanger** [comment]
Hi,

Currently, I write it by hand.
I did not find a crate which get the job like I want :)

**Comment by mjm918** [comment]
Thank you for the fast response ❤️
